In [1]:
import pandas as pd

df = pd.read_csv("adult.csv", header=None)

In [2]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
df.columns = [
    'age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'race', 'sex',
    'capital_gain', 'capital_loss', 'hours_per_week',
    'native_country', 'income'
]

In [4]:
print(df.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [5]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [6]:
df['income'] = df['income'].map({'<=50K': 0, '>50K': 1})

In [7]:
categorical_features = df.select_dtypes(include='object').columns
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns

print("Categorical Features:", categorical_features)
print("Numerical Features:", numerical_features)

Categorical Features: Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country'],
      dtype='object')
Numerical Features: Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week', 'income'],
      dtype='object')

In [8]:
df['income'] = df['income'].map({'<=50K': 0, '>50K': 1})

In [9]:
df = pd.get_dummies(
    df,
    columns=[
        'workclass',
        'marital_status',
        'occupation',
        'relationship',
        'race',
        'sex',
        'native_country'
    ],
    drop_first=True
)

In [10]:
for col in numerical_features:
    mean = df[col].mean()
    std = df[col].std()
    df[col] = (df[col] - mean) / std

In [11]:
df[numerical_features].describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income
count,3.256100e+04,3.256100e+04,3.256100e+04,3.256100e+04,3.256100e+04,3.256100e+04,0.0
mean,-5.193611e-17,-9.907141e-17,1.418423e-16,1.462067e-17,3.644257e-17,-2.727737e-17,NaN
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,NaN
min,-1.582182e+00,-1.681605e+00,-3.529602e+00,-1.459182e-01,-2.166562e-01,-3.193981e+00,NaN
25%,-7.757560e-01,-6.816805e-01,-4.200532e-01,-1.459182e-01,-2.166562e-01,-3.542890e-02,NaN
50%,-1.159528e-01,-1.082176e-01,-3.135955e-02,-1.459182e-01,-2.166562e-01,-3.542890e-02,NaN
75%,6.904732e-01,4.478697e-01,7.460277e-01,-1.459182e-01,-2.166562e-01,3.695137e-01,NaN
max,3.769554e+00,1.226837e+01,2.300802e+00,1.339437e+01,1.059334e+01,4.742894e+00,NaN

In [12]:
df.to_csv("adult_income_processed.csv", index=False)